### ISSUE TITLE
Qliksense Governance

### ISSUE THREAD

**Issue by ravinder765** [rvspt/QlikSenseGovernance#1]
Hello,

I'm trying to extract the metadata files but when it is loading connections list its getting stopped over there. Steps implemented: 1) Installed Node.js 4.5.0 version 2) Exported the Certificates 3) installed qsocks in node modules 4) created appstructures and governanceQVD's folder structure 5) Command used node apps-info.js -a "xxxxxxxx" -ud "xxxxxxxx" -ud "xxxxxxxx"

I'm facing some issues with the connections list which is not getting loaded, could some one help me with this.

Thanks,
 Ravinder

**Comment by rvspt** [comment]
Hello Ravinder, in a few days I'll release something that hopefully might help. This project suffered several updates and is near to be released on a second major version.

**Comment by ravinder765** [comment]
Hello Renato ,
Thanks for the Update and will wait for update on new release.

Thanks,
Ravinder

**Comment by ravinder765** [comment]
Renato,

I've also tested the new released version but when i am trying to execute a command 
node apps-info.js -a "XXXXXX' -ud "XXXX" un "xxxx"

I am getting a error like  below
![image](https://cloud.githubusercontent.com/assets/24437708/21621195/e62013f2-d1c5-11e6-9c0d-2c7c1d862e68.png)


Can you help how to come out of this

I've package installed js2xmlparser as well


Thanks,
Ravinder

**Comment by ravinder765** [comment]
Hi Renato,

I was eagerly waiting for your new release please let me know any updates on that.

Thanks,
Ravinder

**Comment by rvspt** [comment]
Hello Ravinder, 

Check the QlikSenseGovernance-v2 branch (https://github.com/rvspt/QlikSenseGovernance/tree/QlikSenseGovernance-v2). 

It is ready to use. The reason it is not public yet is that we are working on creating an installer to ease the installation process.

Cheers

**Comment by ravinder765** [comment]
Hello Renato,

Thanks for your Quick response. I will test this and i will get back to you if i ran into any issues.

Thanks,
Ravinder

**Comment by ravinder765** [comment]
Hello Renato,

When i was running this command from NodeJS " node apps-info.js -a "XXXX" -ud "xxxxx" -un "XXXXX". i see the below error.

![image](https://cloud.githubusercontent.com/assets/24437708/22349534/0e74f2ee-e3de-11e6-8054-4bb27777e57f.png)


Could please suggest how to resolve this.

Thanks,
Ravinder

**Comment by ravinder765** [comment]
Renato,

Can i have your time to do web-ex on this. If you could help us that would be much appreciated. 

Thanks,
Ravinder
